version: "3"
services:
  app:
    container_name: binary-analysis
    build: .
    security_opt:
    - seccomp:unconfined
    cap_add:
    - SYS_PTRACE
    tty: true
    volumes:
    - type: bind
      source: ./working
      target: /binary-analysis/working
      bind:
        create_host_path: true
